global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "gry-backend"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["backend:8080"]

  - job_name: "gry-frontend"
    static_configs:
      - targets: ["frontend:80"]